### ISSUE TITLE
switch away from set-output command

### ISSUE THREAD

**Issue by bahmutov** [bahmutov/cypress-examples#147]
```yml
- name: Set Cypress version 🎁
  id: cypress
  run: echo "::set-output name=version::$(node ./src/print-cypress-version)"

- name: Print Cypress version 🖨
  run: echo "Cypress version is ${{ steps.cypress.outputs.version }}"
```
<img width="1169" alt="Screenshot 2023-03-17 at 10 48 00" src="https://user-images.githubusercontent.com/2212006/225938715-4e1cf577-51ea-4745-9a70-6c1ac862c363.png">
